---

arch: 'x86_64'

pkgbuild: '/PKGBUILD'

repos:
  - name: 'goblins'
    vcs: 'staging'
    arch: 'staging-x86_64'
    any: 'staging-any'
  - name: 'gremlins'
    vcs: 'testing'
    arch: 'testing-x86_64'
    any: 'testing-any'
  - name: 'system'
    vcs: 'core'
    arch: 'core-x86_64'
    any: 'core-any'
  - name: 'world'
    vcs: 'extra'
    arch: 'extra-x86_64'
    any: 'extra-any'
  - name: 'galaxy-goblins'
    vcs: 'community-staging'
    arch: 'community-staging-x86_64'
    any: 'community-staging-any'
  - name: 'galaxy-gremlins'
    vcs: 'community-testing'
    arch: 'community-testing-x86_64'
    any: 'community-testing-any'
  - name: 'galaxy'
    vcs: 'community'
    arch: 'community-x86_64'
    any: 'community-any'
  - name: 'lib32-goblins'
    vcs: 'multilib-staging'
    arch: 'multilib-staging-x86_64'
  - name: 'lib32-gremlins'
    vcs: 'multilib-testing'
    arch: 'multilib-testing-x86_64'
  - name: 'lib32'
    vcs: 'multilib'
    arch: 'multilib-x86_64'
  - name: 'kde-wobble'
    vcs: 'kde-unstable'
    arch: 'kde-unstable-x86_64'
    any: 'kde-unstable-any'
  - name: 'gnome-wobble'
    vcs: 'gnome-unstable'
    arch: 'gnome-unstable-x86_64'
    any: 'gnome-unstable-any'

tools:
    cmdBuild: 'buildpkg -C'
    cmdRepoAdd: 'deploypkg -a -l'
    cmdRepoRemove: 'deploypkg -r -l'
    cmdSign: 'signpkg'
    cmdYaml: 'pkg2yaml -d'

src:
    repoPath: 'trunk'
    repoName: 'trunk'
    repoAddName: 'default'
    repoRemoveName: 'default'
    isNextLayout: false

author:
    name: ''
    email: ''
    gpgkey: ''

actions:
    isAdd: false
    isRemove: false
    isBuild: false
